name: "Fritz 1200 Device Tracker"
description: "Uses the build-in API of the Fritz 1200 repeater to track connected devices"
url: https://github.com/JohannVR/JohannVRs-Home-Assistant-Addons/tree/main/Fritz-API
version: "1.0.0"
slug: "fritzapitracker"
init: false
arch:
  - aarch64
  - amd64
  - armv7
boot: "auto"
host_network: true
options:
  repeater_ip: "192.168.178.2"
  mqtt_ip: "127.0.0.1"
  mqtt_user: "user"
  mqtt_password: "password"
  device_name_list: "device1, device2"
  device_mac_list: "00:11:22:33:44:55, aa:bb:cc:dd:ee:ff"
schema:
  repeater_ip: str
  mqtt_ip: str
  mqtt_user: str
  mqtt_password: password
  device_name_list: str
  device_mac_list: str
