name: "Airplay 2 for Home Assistant (Alpine)"
description: "Adds Airplay 2 capabilities to Home Assistant"
url: https://github.com/JohannVR/JohannVRs-Home-Assistant-Addons/tree/main/Airplay2Alpine
version: "0.1.0"
slug: "airplay2alpine"
init: false
arch:
  - aarch64
#  - amd64
#  - armv7
boot: "auto"
host_network: true
audio: true
options:
  airplay_name: "Hass.io"
  offset: "0.0"
  enabled: "no"
  mqtt_host: "core-mosquitto"
  mqtt_username: "user"
  mqtt_password: "password"
schema:
  airplay_name: str
  offset: str
  enabled: str
  mqtt_host: str
  mqtt_username: str
  mqtt_password: password
image: "johannvr/ha-airplay2-{arch}-alpine"