name: Publish Docker Images using HA builder

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Publish Docker Images
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --docker-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password ${{ secrets.DOCKERHUB_TOKEN }} \
            --docker-hub-check \
            --target Airplay2 \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }} \
            --image ha-airplay2-{arch}-debian \
